# computational bottleneck
- id: doi:10.1523/ENEURO.0431-23.2024
  image: https://www.eneuro.org/content/eneuro/12/4/ENEURO.0431-23.2024/F2.medium.gif
  tags:
    - basal-ganglia
  buttons:
    - type: source
      text: Code
      link: https://github.com/mdhumphries/Basal_Ganglia_Bottleneck_simulations

# motor cortex spatial and temporal parameters arm movement
- id: doi:10.1523/JNEUROSCI.1777-23.2024
  image: images/JNeurosci_cover.png
  tags:
    - latent-dynamics
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Motor_Cortex_Simultaneous_Coding
    - type: data
      text: Target task data
      link: https://dandiarchive.org/dandiset/000688
      
# Strategy Tracker paper
- id: doi:10.7554/eLife.86491
  image: https://iiif.elifesciences.org/lax:86491%2Felife-86491-fig1-v2.tif/full/617,/0/default.webp
  tags:
    - Bayesian
    - behaviour
  buttons:
    - type: package
      text: MATLAB toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_MATLAB
    - type: package
      text: Python toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_Python
    - type: data
      text: Y-maze data
      link: http://dx.doi.org/10.6080/K0KH0KH5
    - type: data
      text: Other task data
      link: http://doi.org/10.17639/nott.7274  
      
# Activity subspaces in mPfC   
- id: doi:10.1523/JNEUROSCI.1412-21.2022
  image: https://www.jneurosci.org/content/jneuro/42/20/4131/F2.medium.gif
  tags:
    - prefrontal-cortex
    - latent-dynamics

# Bayesian inference of connections between neurons
- id: doi:10.1523/jneurosci.1487-21.2021
  image: https://www.jneurosci.org/content/jneuro/42/8/1417/F10.medium.gif
  tags:
    - basal-ganglia
    - Bayesian
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Bayesian-map-of-striatum-circuitry

# Spectral estimation for networks
- id: doi:10.1371/journal.pone.0254057
  image: images/Paper_Figures/Fig8_of_Spectral_PLoSOne_paper.png
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/NetworkNoiseRejection

# weak-strong principles
- id: doi:10.51628/001c.24619
  image: images/Paper_Figures/DimensionScalingSketch.png
  tags:
    - latent-dynamics

# The Spike
- id: isbn:9780691195889
  image: images/TheSpike_book_cover.jpg
  tags:
    - latent-dynamics

# EJN maladaptive striatal plasticity
- id: doi:10.1111/ejn.14414
image: https://onlinelibrary.wiley.com/cms/asset/9f9b9338-eb44-4912-a18f-0d4432f75952/ejn14414-fig-0003-m.jpg
tags:
    - basal-ganglia
    - dopamine
    
# mPfC plastic irrespective of learning
- id: doi:10.1523/jneurosci.1370-17.2019
  image: https://www.jneurosci.org/content/jneuro/39/18/3470/F3.medium.gif
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/PfCDictionary

# Ensemble code in mPfC
- id: doi:10.1038/s41467-018-04638-2
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-04638-2/MediaObjects/41467_2018_4638_Fig5_HTML.jpg?as=webp
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/sibangi/PFCensemble_ITI

# JNNP BG modelling in PD review
- id: doi: 10.1136/jnnp-2017-315922
  image: https://jnnp.bmj.com/content/jnnp/89/11/1181/F1.medium.gif
  tags:
    - basal-ganglia
    - dopamine

# PLoS CB recursive decision making
- id: doi:10.1371/journal.pcbi.1006033
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=10.1371/journal.pcbi.1006033.g001
  tags:
    - basal-ganglia

# Aplysia spiral attractor
- id: doi:10.7554/eLife.27342
  image: https://iiif.elifesciences.org/lax/27342%2Felife-27342-fig4-v1.tif/full/617,/0/default.webp
  tags:
    - Aplysia
    - latent-dynamics
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/AplysiaAttractorAnalysis
    - type: data
      text: Data
      link: http://dx.doi.org/10.6080/K0SN074B

# dynamical networks
- id: 10.1162/NETN_a_00020
  image: https://mitp.silverchair-cdn.com/mitp/content_public/journal/netn/1/4/10.1162_netn_a_00020/3/m_00020f01c.png?Expires=1750198776&Signature=fVWXQs68YHPFM00qtVQA-JrJfUv5nN1d1onqLB3TkY-MFGqAhz5MwBC5hd4MmEkEuNWyN7TCqGxZSnTdWKqImRm54b89yb-b40qJBpiV8R8UL5DVjuEZihVwCWVUr7uIba6-Ww9i8Jc1ufrK8LGETW6M~Y7qCsleban~sXIC5fSbC~bm9ddO6RqnxbLkuI2YSG18r0WMX1tfZ5fCmxix4zvoZ5kKtv4~XVT8MyxK1kVznoowFnz1iPKTLvUW8gpa2SK2P1hkH5Mq6McxO--nKnTYGzc2Fk1bLGxMYsOmfotEnrdVl4kNQl-zQ3rRyBO4W-TU8E6sWSbkCXRpOUBbaA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
   - network-theory
   - latent-dynamics


# Aplysia modular deconstruction
- id: doi:10.1016/j.neuron.2015.03.005
  image: https://www.cell.com/cms/attachment/b96fd54f-79f3-4c70-9a03-eabfab3f94fd/gr2.jpg
  tags:
    - Aplysia
    - latent-dynamics
    - network-theory
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/NeuralEnsembleAnalysis

# PLoS Biol: CS plasticity model
- id: doi:10.1371/journal.pbio.1002034
  image: https://journals.plos.org/plosbiology/article/figure/image?size=inline&id=10.1371/journal.pbio.1002034.g011
  tags:
    - basal-ganglia
    - dopamine

# sparse communities
- id: doi:10.1038/srep08828
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fsrep08828/MediaObjects/41598_2015_Article_BFsrep08828_Fig2_HTML.jpg?as=webp
  tags:
    - network-theory

# Prog Neurobiol cortical activity distributions
- id: doi:10.1016/j.pneurobio.2012.09.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0301008212001505-gr13.jpg
  tags:
    - latent-dynamics
  buttons:
    - type: paper
      text: Download paper
      link: research/Wohrer2013.pdf

# DA exploit-explore via BG
- id: pmid:22347155
  image: https://images-provider.frontiersin.org/api/ipx/w=290&f=webp/https://www.frontiersin.org/files/Articles/16922/fnins-06-00009-HTML/image_m/fnins-06-00009-g003.jpg
  tags:
    - dopamine
    - basal-ganglia

# MNAS book chapter 
- id: doi:10.1017/CBO9780511731525.018
  image: images/scheibel_dendrites_edit.png
  tags:
    - reticular-formation
    - action-selection
  buttons:
    - type: paper
      text: Download paper
      link: research/Humphries2011a.pdf

# PLoS One small-world-ness
- id: doi:10.1371/journal.pone.0002051
  image: https://journals.plos.org/plosone/article/figure/image?size=inline&id=10.1371/journal.pone.0002051.g001
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/SmallWorldNess 


      
# papers to remove from ORCID: bioRxiv versions of published papers

  
# bottleneck preprint
- id: doi:10.1101/2024.10.23.619790
  remove: true

# motor cortex simultaneous coding pre-print
- id: doi:10.1101/2023.05.26.542452
  remove: true

# later removals:
# EJN maladaptive
# - id: doi:10.1111/ejn.14414
#  remove: true

# JNNP review
# - id: doi:10.1136/jnnp-2017-315922
#  remove: true

# Javier's PLoS CB paper:
# - id: doi:10.1371/journal.pcbi.1006033
#  remove: true

# Networks neural dynamics
# - id: 10.1162/NETN_a_00020
#  remove: true

# sparse networks
- id: pmid:25742951
  remove: true

# Kevin's PLoS Biol 
- id: pmid:25562526
  remove: true
  
# initial removals when setting up website
- id: doi:10.1101/2022.08.30.505807
  remove: true

- id: doi:10.1101/2021.06.08.447507
  remove: true

- id: doi:10.1101/668962
  remove: true

- id: doi:10.1101/543678
  remove: true

- id: doi:10.1101/260992
  remove: true

- id: doi:10.1101/187948
  remove: true

- id: doi:10.1101/115485
  remove: true

- id: doi:10.1101/104562
  remove: true

- id: doi:10.1101/027102
  remove: true

- id: pmid:25819612
  remove: true
