id: doi:10.1523/jneurosci.1487-21.2021
  image: https://www.jneurosci.org/content/jneuro/42/8/1417/F10.medium.gif
  tags:
    - basal ganglia
    - Bayesian
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Bayesian-map-of-striatum-circuitry
