- id: doi:10.7554/eLife.86491
  image: https://iiif.elifesciences.org/lax:86491%2Felife-86491-fig1-v2.tif/full/617,/0/default.webp
  tags:
    - Bayesian
    - behaviour
  buttons:
    - type: package
      text: MATLAB toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_MATLAB
    - type: package
      text: Python toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_Python
    - type: data
      text: Y-maze data
      link: http://dx.doi.org/10.6080/K0KH0KH5
    - type: data
      text: Other task data
      link: http://doi.org/10.17639/nott.7274  
      
- id: doi:10.1523/JNEUROSCI.1412-21.2022
  image: https://www.jneurosci.org/content/jneuro/42/20/4131/F2.medium.gif
  tags:
    - prefrontal-cortex
    - latent-dynamics
      
- id: doi:10.1523/jneurosci.1487-21.2021
  image: https://www.jneurosci.org/content/jneuro/42/8/1417/F10.medium.gif
  tags:
    - basal-ganglia
    - Bayesian
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Bayesian-map-of-striatum-circuitry

- id: doi:10.1371/journal.pone.0254057
  image: https://journals.plos.org/plosone/article/figure/image?size=inline&id=10.1371/journal.pone.0254057.g001
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/NetworkNoiseRejection

- id: doi:10.51628/001c.24619
  image: images/Paper_Figures/DimensionScalingSketch.png
  tags:
    - latent-dynamics

- id: doi:10.1523/jneurosci.1370-17.2019
  image: https://www.jneurosci.org/content/jneuro/39/18/3470/F3.medium.gif
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/PfCDictionary

- id: doi:10.1038/s41467-018-04638-2
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-018-04638-2/MediaObjects/41467_2018_4638_Fig5_HTML.jpg?as=webp
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/sibangi/PFCensemble_ITI

- id: doi:10.7554/eLife.27342
  image: https://iiif.elifesciences.org/lax/27342%2Felife-27342-fig4-v1.tif/full/617,/0/default.webp
  tags:
    - Aplysia
    - latent-dynamics
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/AplysiaAttractorAnalysis
    - type: data
      text: Data
      link: http://dx.doi.org/10.6080/K0SN074B

- id: doi:10.1016/j.neuron.2015.03.005
  image: https://www.cell.com/cms/attachment/b96fd54f-79f3-4c70-9a03-eabfab3f94fd/gr2.jpg
  tags:
    - Aplysia
    - latent-dynamics
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/NeuralEnsembleAnalysis

- id: doi:10.1016/j.pneurobio.2012.09.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0301008212001505-gr13.jpg
  tags:
    - latent-dynamics
  buttons:
    - type: paper
      text: Download paper
      link: research/Wohrer2013.pdf

- id: pmid:22347155
  image: https://images-provider.frontiersin.org/api/ipx/w=290&f=webp/https://www.frontiersin.org/files/Articles/16922/fnins-06-00009-HTML/image_m/fnins-06-00009-g003.jpg
  tags:
    - dopamine
    - basal-ganglia

# MNAS book chapter 
- id: doi:10.1017/CBO9780511731525.018
  tags:
    - reticular-formation
    - action-selection
  buttons:
    - type: paper
      text: Download paper
      link: research/Humphries2011a.pdf

- id: doi:10.1371/journal.pone.0002051
  image: https://journals.plos.org/plosone/article/figure/image?size=inline&id=10.1371/journal.pone.0002051.g001
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/SmallWorldNess 
      
# papers to remove from ORCID: bioRxiv versions of published papers
- id: doi:10.1101/2022.08.30.505807
  remove: true

- id: doi:10.1101/2021.06.08.447507
  remove: true

- id: doi:10.1101/668962
  remove: true

- id: doi:10.1101/543678
  remove: true

- id: doi:10.1101/260992
  remove: true

- id: doi:10.1101/187948
  remove: true

- id: doi:10.1101/115485
  remove: true

- id: doi:10.1101/104562
  remove: true

- id: doi:10.1101/027102
  remove: true

# - id pubmed:25819612
#  remove: true
