id: doi:10.1523/jneurosci.1487-21.2021
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  tags:
    - basal ganglia
    - Bayesian
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Bayesian-map-of-striatum-circuitry
